# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Actualizaciones para Node.js (package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "npm"

  # Actualizaciones para GitHub Actions (.github/workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "actions"
